config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :activities do
    resources :orders, only: :create
  end

  get '/orders/approved', to: 'orders#approved'

  get '/user_profile', to: 'pages#user_profile'
  get '/user_orders', to: 'orders#user_orders'
  get '/user_sales', to: 'orders#user_sales'

  root to: 'pages#home'
end

app/models/activity.rb
class Activity < ApplicationRecord
  ACTIVITY_CATEGORIES = ["Aniversário", "Ar livre", "Desporto", "Cozinha", "Livros", "Online", "Outros"]
  belongs_to :user
  has_many :orders
  has_many_attached :photos

  validates :title, presence: true, length: { maximum: 150 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :category, presence: true, inclusion: { in: ACTIVITY_CATEGORIES }
  validates :duration, length: { maximum: 50 }
  validates :min_age, presence: true, length: { maximum: 2 }
  validates :price, length: { maximum: 10 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :activities
  has_many :orders
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_activity, only: %i[show edit update destroy]

  def index
    category = params[:category]
    if category.present?
      @activities = Activity.where(category: category)
    else
      @activities = Activity.all
    end
    activities_lat_lng(@activities)
  end

  def show
    @order = Order.new
    activities_lat_lng(@activity)
  end

  def new
    @activity = Activity.new
    @user = current_user
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @activity.update(activity_params)
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:title, :description, :category, :duration, :min_age, :price, :photo)
  end

  def activities_lat_lng(activities)
    if !activities.is_a?(Activity)
      @map_markers = activities.geocoded.map { |activity| { lat: activity.latitude, lng: activity.longitude } }
    elsif activities.latitude.present? && activities.longitude.present?
      activities = [activities]
      @map_markers = activities.map { |activity| { lat: activity.latitude, lng: activity.longitude } }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo address])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @user = current_user
    @order = Order.new
    @order.user = @user
    @order.activity = Activity.find(params[:activity_id])
    if @order.save
      redirect_to orders_approved_path
    else
      redirect_to activity_path(@order.activity)
    end
  end

  def approved
    @user = current_user
  end

  def user_orders
    @user = current_user
    @user_orders = @user.orders
  end

  def user_sales
    @orders = Order.all
    @user = current_user
    @user_activities = Activity.where(user_id: @user.id)

    @user_sales = @orders.select do |order|
      @user_activities.each do |activity|
        order.activity_id == activity.id
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def user_profile
    @user = current_user
    @user_activities = @user.activities
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/__show.html.erb
<div class="container">
  <h1>Activities#show</h1>
  <p>Find me in app/views/activities/show.html.erb</p>
  <%= @activity.title %>
  <hr>
  <%= @activity.description %>
  <hr>
  <%= @activity.category %>
  <hr>
  <%= @activity.duration %>
  <hr>
  <%= @activity.min_age%>
  <hr>
  <%= @activity.price%>
  <hr>
  <%= simple_form_for([@activity, @order]) do |f| %>
    <%= f.submit %>
  <% end %>
</div>

app/views/activities/edit.html.erb
<div class="container">
  <%= render('/shared/activity-form', activity: @activity) %>
<div>

app/views/activities/index.html.erb
<div class="index-page-content">
  <div class="title">
    <%# <h3>Como podemos lhe ajudar hoje?</h3>
    <p>Escolhe uma categoria</p> %>
  </div>
  <div class="category">
    <div class="dropdown">
      <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categorias
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <%= link_to("Todas", activities_path, class: "dropdown-item") %>
        <% Activity::ACTIVITY_CATEGORIES.each do |category| %>
          <%= link_to("#{category}", activities_path(category: "#{category}"), class: "dropdown-item") %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="cards">
    <% @activities.each do |activity| %>
      <%= render('shared/card-activity', activity: activity) %>
    <% end %>
  </div>
  <div id="map" class="map-index" data-markers="<%= @map_markers.to_json %>">
  </div>
</div>

app/views/activities/new.html.erb
<div class="container">
  <%= render('/shared/activity-form', activity: @activity) %>
<div>

app/views/activities/show.html.erb
<main class="container show-page-content">
  <div class="images images-carousel">
    <% @activity.photos.each do |photo| %>
      <%= cl_image_tag(photo.key, height: 400, gravity: "faces", crop: "fill")%>
    <% end %>
  </div>
  <div class="act-title">
    <h1><%= @activity.title %> <%= render('shared/category-badge', category: @activity.category) %></h1>
    <div>
      <i class="fas fa-edit"></i>
      <%= link_to(activity_path(@activity), method: :delete, data: {confirm: "Atividade será apagada, têm certeza"}) do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
  <div class="content">
    <p><%= @activity.description %></p>
    <span>
      <h6>Experiência oferecida por <strong><%= @activity.user.name %></strong></h6>
      <%= cl_image_tag(@activity.user.photo.key, class: "card-trip-user avatar-bordered") %>
    </span>
    <div class="act-specs">
      <% if @activity.duration.present? %>
        <span><i class="fas fa-clock"></i> <%= @activity.duration %></span>
      <% end %>
      <span><i class="fas fa-child"></i> <%= @activity.min_age %>+ anos</span>
    </div>
  </div>
  <div class="booking">
    <p><strong><%= number_to_currency(@activity.price, unit: "R$ ", separator: ",", delimiter: "") %></strong></p>
    <%= simple_form_for([@activity, @order]) do |f| %>
      <%= f.submit %>
    <% end %>
  </div>
  <div id="map" class="map-show" data-markers="<%= @map_markers.to_json %>">
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KidsTime - Ideias criativas para momentos especiais recomendadas por outros pais</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Mapbox -->
    <%= stylesheet_link_tag 'https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css', media: 'all'%>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <!-- Navbar -->
    <header>
      <%= render('shared/navbar') %>
      <%= render('shared/flashes') %>
    </header>
    <!-- Page content -->
    <%= yield %>
    <!-- Footer -->
    <footer>
      <%= render('shared/footer') %>
    </footer>
  </body>
</html>

app/views/orders/approved.html.erb
<div class="container col-6">
  <div class="d-flex container bg-info align-items-center justify-content-center " >
    <div class="container col-10 mt-4 mb-4 row align-items-center justify-content-center" style= "border-radius: 10px; height: 350px;background-color: white; padding-left: 30px;">
      <h5 style="text-align: center;">Sua encomenda foi aprovada!</h5>
      <iframe class="fixed-ratio-resize" style= " max-width: 100%;height: auto; width: auto\9;" src="https://giphy.com/embed/BwX4rgf3rfWz6" width="480" height="480" frameBorder="0" ></iframe>
    </div>
  </div>
</div>

app/views/orders/user_orders.html.erb
<div class="container">
  <div class="container justify-content-center">
    <h5 class="mt-4 mb-3 justify-content-center">Meu histórico de compras</h5>
    <% @user_orders.each do |order| %>
      <%= render('shared/card-activity', act_photo: order.activity.photo.present? ? order.activity.photo.key : false, title: order.activity.title, category: order.activity.category, price: order.activity.price, act_user_photo:  order.activity.user.photo.present? ? order.activity.user.photo.key : false) %>
    <% end %>
  </div>
</div>

app/views/orders/user_sales.html.erb
<div class="container">
  <% @user_sales.each do |sale| %>
    <p><%= sale.activity.price %></p>
  <% end %>
</div>

app/views/pages/home.html.erb
<main class="home-page-content">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= image_url('spikeball.jpg')%>)">
    <div class="container">
      <h1>Kids Time seja <strong>criativo</strong> na <strong>educação do seus filhos</strong>!</h1>
      <p>Encontre ideias diferentes e para produtos e serviços recomendados por outros pais e viva momentos especiais com seus filhos!</p>
      <%= link_to("Descubra atividades agora", activities_path, class: "btn-home-banner") %>
    </div>
    
  </div>
</main>

app/views/pages/user_profile.html.erb
<div class="d-flex container mt-4 ">
  <div class="container bg-info col-3" style= "border-radius: 10px; height: 450px;">
    <div class="mt-3 text-center">
      <% if @user.photo.present? %>
        <%= cl_image_tag(@user.photo.key, transformation: [{width: 400, height: 400, gravity: "face", radius: "max", crop: "fill", quality: 80}, {width: 150, crop: "scale"}], class: "avatar-large") %>
      <% else %>
        <%= image_tag('avatar.png') %>
      <% end %>
      <h5><%= @user.name %></h5>
    </div>
    <div class="container">
      <div class="border-bottom mt-3">
        <p><i class="fas fa-star star-profile mr-3 " style="color:#7A75FC;"></i>9 Reviews <br>
          <i class="fas fa-check check-profile mr-3 text-success"></i>Identidade verificada</p>
      </div>
      <div class="mt-3">
        <%= link_to('#') do %>
          <p class= "text-dark"><i class="fas fa-heart mr-3 text-danger"></i>Minha wishlist</p>
        <% end %>
      </div>
      <div class="">
        <%= link_to(user_orders_path) do %>
          <p class= "text-dark"><i class="fas fa-shopping-bag mr-3 text-primary"></i>Minhas compras</p>
        <% end %>
      </div>
      <div class="">
        <%= link_to(user_sales_path) do %>
          <p class= "text-dark"><i class="fas fa-store mr-3 text-success"></i>Minhas vendas</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container ml-5 col-lg-8">
    <h4>Meu perfil</h4>
    <div class= "container-custom my-4 border py-4 p-3" style= "border-radius: 10px;">
      <h5>Ola, prazer! Sou a <%= @user.name %></h5>
      <div class="d-flex flex-wrap btns-category" style= "justify-content:space-around;">
        <div>
          <%= link_to "em casa", root_path, class: 'btn-tag1 display:inline-block hvr-grow' %>
        </div>
        <div>
          <%= link_to "na cozinha", root_path, class: 'btn-tag4 hvr-grow' %>
        </div>
        <div>
          <%= link_to "ar livre", root_path, class: 'btn-tag2 display:inline-block hvr-grow' %>
        </div>
      </div>
      <p>Moro em Sao Paulo, tenho dois filhos de 8 & 10 anos com muita energia! Sou cantora e adoro tocar ukulele com meus filhos. Com eles, me  tornei profissional em montar os pratos mais divertidos e brincar de geoguesser.</p>
    </div>
    <div class="row d-flex justify-content-between col-9 align-items-center mb-3">
      <h4>Minhas atividades</h4>
      <div>
        <%= link_to "Adicionar", new_activity_path, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="d-flex justify-content-between flex-wrap">
      <% @user_activities.each do |activity| %>
        <%= link_to(activity_path(activity)) do %>
          <%= render('shared/card-activity', act_photo: activity.photo.present? ? activity.photo.key : false, title: activity.title, category: activity.category, price: activity.price, act_user_photo:  activity.user.photo.present? ? activity.user.photo.key : false) %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_activity-form.html.erb
<div class= "container bg-info" >
  <div class="row justify-content-center">
    <div class="bg-light col-6 my-4 py-4" style= "border-radius: 10px;">
      <h4 style="margin-bottom: 15px; text-align: center;">Detalhes da Atividade</h4>
      <%= simple_form_for(activity) do |f| %>
      <div>
        <%= f.input :category, label:"Categoria", collection: ACTIVITY_CATEGORIES %>
      </div>
      <div class= "d-flex justify-content" style= "justify-content:space-between;">
        <%= f.input :title, label:"Título" %>
        <%= f.input :min_age, label:"Idade mínima" %>
      </div>
        <%= f.input :description, label:"Descrição" %>
      <div class= "d-flex justify-content" style= "justify-content:space-between;">
        <%= f.input :duration, label:"Duração" %>
        <%= f.input :price, label:"Preço" %>
      </div>
      <div>
        <%= f.input :photo, label:"Foto", as: :file %>
      </div>
      <div class="form-actions">
        <%= f.submit "Submeter", class: 'btn btn-create btn-block mt-4' %>
      </div>
      <% end %>
    </div>
</div>
</div>

app/views/shared/_activity_form.html.erb
<%= simple_form_for(@activity) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :category, collection: ACTIVITY_CATEGORIES %>
    <%= f.input :duration %>
    <%= f.input :min_age %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
<% end %>

app/views/shared/_card-activity.html.erb
<div class="card-trip">
  <% if activity.photos.present? %>
    <div class='cardActivityCarousel images-carousel'>
      <% activity.photos.each do |photo| %>
        <%= cl_image_tag(photo.key, :width=>300, :height=>250, :gravity=>"faces", :crop=>"fill")%>
      <% end %>
    </div>
  <% else %>
    <%= image_tag('placeholder.png') %>
  <% end %>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to(activity.title, activity_path(activity)) %></h2>
      <%= render("shared/category-badge", category: activity.category) %>
      <p>
        <% if activity.duration.present? %>
          <i class="fas fa-clock"></i> <%= activity.duration %>
        <% end %>
        <i class="fas fa-child"></i> <%= activity.min_age %>+ anos
      </p>
    </div>
    <h2 class="card-trip-pricing"><%= number_to_currency(activity.price, unit: "R$ ", separator: ",", delimiter: "") %></h2>
    <% if activity.user.photo.present? %>
      <%= cl_image_tag(activity.user.photo.key, class: "card-trip-user avatar-bordered") %>
    <% else %>
      <%= image_tag('avatar.png', class: "card-trip-user avatar-bordered") %>
    <% end %>
  </div>
</div>

app/views/shared/_category-badge.html.erb
<%= link_to("#{category}", activities_path(category: "#{category}"), class: "category-badge") %>

app/views/shared/_flashes.html.erb
<% if success %>
  <div class="container">
    <div class="flash flash-success alert alert-dismissible fade show" role="alert">
      <span><strong>Yay!</strong> 🎉 <%= success %>.</span>
      <a data-dismiss="alert" aria-label="Close"><i class="fas fa-times"></i></a>
    </div>
  </div>
<% end %>

<% if notice %>
  <div class="container">
    <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
      <span><strong>Hey</strong> 🙂 <%= notice %></span>
      <a data-dismiss="alert" aria-label="Close"><i class="fas fa-times"></i></a>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="container">
    <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
      <span><strong>Oops!</strong> 😱 <%= alert %></span>
      <a data-dismiss="alert" aria-label="Close"><i class="fas fa-times"></i></a>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <%= link_to("https://github.com/jmschp/kids-time", target: "blank") do %>
      <i class='fab fa-github'></i>
    <% end %>
    <p>Kids Time <i class="fas fa-heart"></i></p>
</div>

app/views/shared/_login-banner.html.erb
<!-- code a container section -->
<div class="login-banner">
  <div class="container">
    <h3>Você criativo na educação do seus filhos</h3>
    <p>Estamos aqui para lhe você encontrar em 5 min atividades criativas para o desenvolvimento do seu filho. Junte-se a nossa comunidade de pais criativos!</p>
    <div class="login-banner-icons">
      <p><i class="fas fa-camera-retro"></i> MOMENTOS INESQUECIVEIS</p>
      <p><i class="fas fa-child"></i> ATIVIDADES ADAPTADAS A IDADE DO SEU FILHO</p>
      <p><i class="fas fa-smile-wink"></i> TESTADAS E APROVADAS POR OUTROS PAIS</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to(root_path, class: "navbar-brand") do %>
    <%= image_tag("logokidstime.png") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to("Home ",root_path, class: "nav-link text-primary") %>
        </li>
        <li class="nav-item">
          <%= link_to("Atividades", activities_path, class: "nav-link text-primary") %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.present? %>
            <%= cl_image_tag(current_user.photo.key, transformation: [{width: 400, height: 400, gravity: "face", radius: "max", crop: "fill", quality: 80}, {width: 150, crop: "scale"}], class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% else %>
            <%= image_tag('avatar.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to("My perfil", user_profile_path, class: "dropdown-item") %>
            <%= link_to("Editar conta", edit_user_registration_path, class: "dropdown-item") %>
            <%= link_to("Minhas compras", user_orders_path, class: "dropdown-item") %>
            <%= link_to("Criar oferta", new_activity_path, class: "dropdown-item") %>
            <%= link_to("Logout", destroy_user_session_path, method: :delete, class: "dropdown-item") %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to("Login / Signup", new_user_session_path, class: "nav-link text-primary") %>
        </li>
      <% end %>
    </ul>
  </div>
</div>